In [10]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0],  # Sample 1: Class 1
    [0, 1, 0],  # Sample 2: Class 2
    [0, 0, 1],   # Sample 3: Class 3
    [0, 1, 0],  # Sample 4: Class 4
    [0, 0, 1],   # Sample 5: Class 5
    ])

In [11]:
# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1],  # Sample 1
    [0.5, 2.5, 0.2],  # Sample 2
    [0.1, 0.2, 3.0],  # Sample 3
    [3.0, 2.0, 0.6],  # Sample 4
    [4.5, 3.5, 0.3],  # Sample 5

])

In [12]:
# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

In [13]:
# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

Softmax Probabilities:
 [[0.65900114 0.24243297 0.09856589]
 [0.10953053 0.80932725 0.08114221]
 [0.04931133 0.05449744 0.89619123]
 [0.68559015 0.25221452 0.06219533]
 [0.72313115 0.26602508 0.01084377]]


In [14]:
# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)


Log of Softmax Probabilities:
 [[-0.41703002 -1.41703002 -2.31703002]
 [-2.21155193 -0.21155193 -2.51155193]
 [-3.00960146 -2.90960146 -0.10960146]
 [-0.37747529 -1.37747529 -2.77747529]
 [-0.32416468 -1.32416468 -4.52416468]]


In [15]:
# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)


y_true * log(probs):
 [[-0.41703002 -0.         -0.        ]
 [-0.         -0.21155193 -0.        ]
 [-0.         -0.         -0.10960146]
 [-0.         -1.37747529 -0.        ]
 [-0.         -0.         -4.52416468]]


In [16]:
# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)


CE Loss per Sample: [0.41703002 0.21155193 0.10960146 1.37747529 4.52416468]


In [17]:
# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)


Average CE Loss for the Dataset: 1.3279646746564342
